CREATE TABLE evidence (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  org_id UUID REFERENCES organizations(id),
  mission_id UUID REFERENCES missions(id),
  title TEXT NOT NULL,
  url TEXT,
  archived_url TEXT,
  perceptual_hash TEXT,
  video_frame_hashes TEXT[],
  hash_sha256 TEXT,
  first_seen_url TEXT,
  first_seen_at TIMESTAMPTZ,
  content_text TEXT,
  source_type TEXT,
  credibility INTEGER CHECK (credibility BETWEEN 1 AND 5),
  verification_status TEXT DEFAULT 'unverified',
  tags TEXT[] DEFAULT '{}',
  geolocation GEOGRAPHY(POINT, 4326),
  geo_verification_status TEXT DEFAULT 'unverified',
  geo_verification_notes TEXT,
  captured_at TIMESTAMPTZ DEFAULT NOW(),
  created_by UUID REFERENCES users(id),
  chain_of_custody JSONB DEFAULT '[]'
);
