'use client'
import { useEffect, useState } from 'react'
const RUNGS = ['De-escalation signals','Backchannel diplomacy','Formal negotiation','Sanctions threat','Sanctions active','Force mobilization','Cross-border incidents','Limited strikes','Sustained campaign','Full conflict']
export function EscalationLadder() {
  const [missionId, setMissionId] = useState('demo-mission')
  const [currentRung, setCurrentRung] = useState(1)
  const [autoAdvance, setAutoAdvance] = useState(false)
  useEffect(() => { void fetch(`/api/v1/escalation?mission_id=${encodeURIComponent(missionId)}`, { cache: 'no-store' }).then((r) => r.json()).then((json: { data?: { current_rung?: number; auto_advance?: boolean } }) => { setCurrentRung(json.data?.current_rung ?? 1); setAutoAdvance(Boolean(json.data?.auto_advance)) }) }, [missionId])
  const save = async (rung: number, auto: boolean) => { await fetch('/api/v1/escalation', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ mission_id: missionId, current_rung: rung, auto_advance: auto }) }) }
  return <div className="rounded-xl border p-4" style={{ borderColor: 'var(--border)', background: 'var(--bg-surface)' }}><div className="mb-4 flex items-center justify-between"><input value={missionId} onChange={(e) => setMissionId(e.target.value)} className="rounded border px-3 py-2 text-sm" style={{ borderColor: 'var(--border)', background: 'var(--bg-surface-2)', color: 'var(--text-primary)' }} /><label className="text-sm" style={{ color: 'var(--text-secondary)' }}><input type="checkbox" checked={autoAdvance} onChange={(e) => { setAutoAdvance(e.target.checked); void save(currentRung, e.target.checked) }} className="mr-2" />Auto-advance</label></div><div className="space-y-2">{RUNGS.map((label, index) => { const rung = index + 1; const active = rung === currentRung; return <button key={label} onClick={() => { setCurrentRung(rung); void save(rung, autoAdvance) }} className="flex w-full items-center gap-3 rounded-lg border p-3 text-left" style={{ borderColor: active ? 'var(--primary)' : 'var(--border)', background: active ? 'var(--primary-dim)' : 'var(--bg-surface-2)' }}><div className="flex h-8 w-8 items-center justify-center rounded-full" style={{ background: active ? 'var(--primary)' : 'var(--bg-base)', color: '#fff' }}>{rung}</div><div><div style={{ color: 'var(--text-primary)' }}>{label}</div>{active ? <div className="text-xs" style={{ color: 'var(--text-muted)' }}>Current position</div> : null}</div></button> })}</div></div>
}
