'use client'
import { useEffect, useState } from 'react'
const RUNGS = ['De-escalation signals','Backchannel diplomacy','Formal negotiation','Sanctions threat','Sanctions active','Force mobilization','Cross-border incidents','Limited strikes','Sustained campaign','Full conflict']
export function EscalationLadder() {
  const [missionId, setMissionId] = useState('demo-mission')
  const [currentRung, setCurrentRung] = useState(1)
  const [autoAdvance, setAutoAdvance] = useState(false)
  useEffect(() => { void fetch(`/api/v1/escalation?mission_id=${encodeURIComponent(missionId)}`, { cache: 'no-store' }).then((r) => r.json()).then((json: { data?: { current_rung?: number; auto_advance?: boolean } }) => { setCurrentRung(json.data?.current_rung ?? 1); setAutoAdvance(Boolean(json.data?.auto_advance)) }) }, [missionId])
  const save = async (rung: number, auto: boolean) => { await fetch('/api/v1/escalation', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ mission_id: missionId, current_rung: rung, auto_advance: auto }) }) }
  return <div className="rounded-xl border border-white/[0.05] bg-white/[0.015] p-4"><div className="mb-4 flex items-center justify-between"><input value={missionId} onChange={(e) => setMissionId(e.target.value)} className="rounded border border-white/[0.05] bg-white/[0.03] px-3 py-2 text-sm text-white" /><label className="text-sm text-white/50"><input type="checkbox" checked={autoAdvance} onChange={(e) => { setAutoAdvance(e.target.checked); void save(currentRung, e.target.checked) }} className="mr-2" />Auto-advance</label></div><div className="space-y-2">{RUNGS.map((label, index) => { const rung = index + 1; const active = rung === currentRung; return <button key={label} onClick={() => { setCurrentRung(rung); void save(rung, autoAdvance) }} className="flex w-full items-center gap-3 rounded-lg border p-3 text-left" style={{ borderColor: active ? '#60a5fa' : '#ffffff05', background: active ? '#3b82f620' : '#ffffff08' }}><div className="flex h-8 w-8 items-center justify-center rounded-full" style={{ background: active ? '#3b82f6' : '#070B11', color: '#fff' }}>{rung}</div><div><div className="text-white">{label}</div>{active ? <div className="text-xs text-white/30">Current position</div> : null}</div></button> })}</div></div>
}
