'use client'
import { useEffect, useState } from 'react'

type ApiData = { summary: Array<{ analyst_id: string; count: number; brier: number }>; calibration_curve: Array<{ bucket: string; predicted: number; actual: number }>; baseline_brier: number }
export function ForecastCalibration() {
  const [data, setData] = useState<ApiData | null>(null)
  useEffect(() => { void fetch('/api/v1/forecasts/calibration', { cache: 'no-store' }).then((r) => r.json()).then((json: { data?: ApiData }) => setData(json.data ?? null)) }, [])
  return <div className="grid gap-6 lg:grid-cols-2"><div className="rounded-xl border p-4" style={{ borderColor: 'var(--border)', background: 'var(--bg-surface)' }}><div className="mb-3 text-sm font-semibold" style={{ color: 'var(--text-primary)' }}>Brier score by analyst / org</div><table className="w-full text-sm"><thead><tr style={{ color: 'var(--text-muted)' }}><th className="px-3 py-2 text-left">Analyst</th><th className="px-3 py-2 text-left">Forecasts</th><th className="px-3 py-2 text-left">Brier</th></tr></thead><tbody>{(data?.summary ?? []).map((row) => <tr key={row.analyst_id} className="border-t" style={{ borderColor: 'var(--border)' }}><td className="px-3 py-2" style={{ color: 'var(--text-primary)' }}>{row.analyst_id}</td><td className="px-3 py-2" style={{ color: 'var(--text-secondary)' }}>{row.count}</td><td className="px-3 py-2" style={{ color: 'var(--text-primary)' }}>{row.brier.toFixed(3)}</td></tr>)}</tbody></table></div><div className="rounded-xl border p-4" style={{ borderColor: 'var(--border)', background: 'var(--bg-surface)' }}><div className="mb-3 text-sm font-semibold" style={{ color: 'var(--text-primary)' }}>Calibration curve vs baseline ({data?.baseline_brier ?? 0.25})</div><table className="w-full text-sm"><thead><tr style={{ color: 'var(--text-muted)' }}><th className="px-3 py-2 text-left">Bucket</th><th className="px-3 py-2 text-left">Predicted</th><th className="px-3 py-2 text-left">Actual</th></tr></thead><tbody>{(data?.calibration_curve ?? []).map((row) => <tr key={row.bucket} className="border-t" style={{ borderColor: 'var(--border)' }}><td className="px-3 py-2" style={{ color: 'var(--text-primary)' }}>{row.bucket}</td><td className="px-3 py-2" style={{ color: 'var(--text-secondary)' }}>{(row.predicted * 100).toFixed(1)}%</td><td className="px-3 py-2" style={{ color: 'var(--text-secondary)' }}>{(row.actual * 100).toFixed(1)}%</td></tr>)}</tbody></table></div></div>
}
