import type { Metadata } from 'next'
import Link from 'next/link'
import { Activity, Bell, Globe, Key, Plane, Radio, Shield, TrendingUp } from 'lucide-react'

export const metadata: Metadata = {
  title: 'Conflict Ops — Geopolitical Intelligence. Built for Operators.',
  description: 'Production-grade geopolitical intelligence for analysts, operators, and security teams.',
}

const FEATURES = [
  { icon: Activity, color: '#60A5FA', title: 'Real-Time Intel Feed', desc: 'Multi-source ingest every 15 minutes across 5 global data streams' },
  { icon: Globe, color: '#22C55E', title: 'Conflict Map', desc: 'PostGIS-powered interactive map with event clustering, AIS vessel positions, and thermal overlays' },
  { icon: TrendingUp, color: '#A78BFA', title: 'AI Forecasting', desc: 'Monte Carlo risk models. P10/P50/P90 scenario outputs. Zero hallucinated predictions.' },
  { icon: Bell, color: '#FB923C', title: 'Alert Engine', desc: 'Define Priority Intelligence Requirements. Get alerted the moment conditions are met.' },
  { icon: Radio, color: '#F87171', title: 'Vessel & Flight Tracking', desc: 'AIS maritime tracking + ADS-B flight data. Dark vessel detection. Military callsign recognition.' },
  { icon: Key, color: '#94A3B8', title: 'REST API + Webhooks', desc: 'Business-tier API with Bearer auth, rate limiting, and HMAC-signed webhooks.' },
]

export default function LandingPage() {
  const ShieldIcon = Shield as any
  return (
    <div style={{ minHeight: '100vh', background: 'var(--bg-base)', color: 'var(--text-primary)', fontFamily: 'Inter, sans-serif' }}>
      <style>{`@keyframes pulse{0%,100%{opacity:1}50%{opacity:.4}}`}</style>
      <nav style={{ position: 'sticky', top: 0, zIndex: 40, backdropFilter: 'blur(14px)', background: 'rgba(7,11,17,0.72)', borderBottom: '1px solid var(--border)' }}><div style={{ maxWidth: 1240, margin: '0 auto', padding: '16px 24px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 24 }}><div style={{ display: 'flex', alignItems: 'center', gap: 10 }}><ShieldIcon size={18} color="#60A5FA" /><span style={{ fontWeight: 700, fontSize: 16 }}>Conflict Ops</span></div><div style={{ display: 'flex', alignItems: 'center', gap: 24 }}><Link href="/features" style={{ color: 'var(--text-secondary)', textDecoration: 'none' }}>Features</Link><Link href="/pricing" style={{ color: 'var(--text-secondary)', textDecoration: 'none' }}>Pricing</Link><Link href="/methods" style={{ color: 'var(--text-secondary)', textDecoration: 'none' }}>Methods</Link><Link href="/wire" style={{ color: 'var(--text-secondary)', textDecoration: 'none' }}>Live Wire</Link><Link href="/sign-in" style={{ color: 'var(--text-primary)', textDecoration: 'none' }}>Sign in</Link><Link href="/sign-up" style={{ textDecoration: 'none', background: 'var(--primary)', color: '#fff', padding: '10px 16px', borderRadius: 10, fontWeight: 600 }}>Start Free</Link></div></div></nav>
      <section style={{ maxWidth: 1240, margin: '0 auto', padding: '96px 24px 72px', textAlign: 'center' }}><div style={{ display: 'inline-flex', alignItems: 'center', gap: 10, padding: '8px 14px', borderRadius: 999, border: '1px solid var(--border)', background: 'var(--bg-surface)' }}><span style={{ color: '#22C55E', animation: 'pulse 1.8s infinite' }}>●</span><span style={{ color: 'var(--text-secondary)', fontSize: 13 }}>Live — GDELT · UN OCHA · NASA · GDACS</span></div><h1 style={{ margin: '24px auto 20px', maxWidth: 940, fontSize: 60, lineHeight: 1.02, fontWeight: 800, letterSpacing: '-0.04em', background: 'linear-gradient(180deg,#F1F5F9 0%,#94A3B8 100%)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>Geopolitical Intelligence. Built for Operators.</h1><p style={{ maxWidth: 560, margin: '0 auto', color: 'var(--text-secondary)', fontSize: 20, lineHeight: 1.55 }}>Data-dense operational awareness, structured analysis, and market-grade forecasting without the enterprise procurement circus.</p><div style={{ display: 'flex', justifyContent: 'center', gap: 14, marginTop: 32 }}><Link href="/sign-up" style={{ textDecoration: 'none', background: 'var(--primary)', color: '#fff', padding: '14px 22px', borderRadius: 12, fontWeight: 600 }}>Start Free</Link><Link href="/wire" style={{ textDecoration: 'none', border: '1px solid var(--border)', color: 'var(--text-primary)', padding: '14px 22px', borderRadius: 12 }}>View Live Feed</Link></div></section>
      <section style={{ borderTop: '1px solid var(--border)', borderBottom: '1px solid var(--border)' }}><div style={{ maxWidth: 1240, margin: '0 auto', padding: '24px', display: 'grid', gridTemplateColumns: 'repeat(4,minmax(0,1fr))', gap: 24 }}><div><div style={{ fontSize: 30, fontWeight: 700, fontFamily: 'JetBrains Mono, monospace' }}>5</div><div style={{ color: 'var(--text-secondary)' }}>Live global sources</div></div><div><div style={{ fontSize: 30, fontWeight: 700, fontFamily: 'JetBrains Mono, monospace' }}>15m</div><div style={{ color: 'var(--text-secondary)' }}>Fast lane ingest</div></div><div><div style={{ fontSize: 30, fontWeight: 700, fontFamily: 'JetBrains Mono, monospace' }}>P10/P50/P90</div><div style={{ color: 'var(--text-secondary)' }}>Scenario outputs</div></div><div><div style={{ fontSize: 30, fontWeight: 700, fontFamily: 'JetBrains Mono, monospace' }}>24/7</div><div style={{ color: 'var(--text-secondary)' }}>Operational visibility</div></div></div></section>
      <section style={{ maxWidth: 1240, margin: '0 auto', padding: '72px 24px' }}><div style={{ display: 'grid', gridTemplateColumns: 'repeat(3,minmax(0,1fr))', gap: 20 }}>{FEATURES.map((feature, idx) => { const Icon = feature.icon as any; return <div key={idx} style={{ padding: 24, borderRadius: 16, border: '1px solid var(--border)', background: 'var(--bg-surface)' }}><div style={{ width: 42, height: 42, borderRadius: 12, background: `${feature.color}20`, display: 'flex', alignItems: 'center', justifyContent: 'center', marginBottom: 16 }}><Icon size={22} color={feature.color} /></div><div style={{ fontSize: 18, fontWeight: 600, marginBottom: 8 }}>{feature.title}</div><div style={{ color: 'var(--text-secondary)', lineHeight: 1.6 }}>{feature.desc}</div></div> })}</div></section>
      <section style={{ maxWidth: 1240, margin: '0 auto', padding: '0 24px 72px' }}><div style={{ overflow: 'hidden', borderRadius: 16, border: '1px solid var(--border)', background: 'var(--bg-surface)' }}><table style={{ width: '100%', borderCollapse: 'collapse' }}><thead><tr><th style={{ textAlign: 'left', padding: 16, color: 'var(--text-muted)' }}>Feature</th><th style={{ textAlign: 'left', padding: 16, background: 'var(--primary-dim)' }}>Conflict Ops</th><th style={{ textAlign: 'left', padding: 16, color: 'var(--text-muted)' }}>Dataminr</th><th style={{ textAlign: 'left', padding: 16, color: 'var(--text-muted)' }}>Feedly TI</th></tr></thead><tbody>{[['Starting price','$9/month','~$10,000/month','$18/month'],['Self-serve signup','✓','✗','✓'],['Structured analysis (ACH, Monte Carlo)','✓','✗','✗'],['Vessel & flight tracking','✓','✓','✗'],['Travel risk / duty of care','✓','✗','✗'],['REST API & webhooks','✓ Business','✓ Enterprise','✓ Paid add-on']].map((row, idx) => <tr key={idx} style={{ borderTop: '1px solid var(--border)' }}><td style={{ padding: 16, color: 'var(--text-secondary)' }}>{row[0]}</td><td style={{ padding: 16, background: 'var(--primary-dim)', color: 'var(--text-primary)', fontWeight: 600 }}>{row[1]}</td><td style={{ padding: 16, color: 'var(--text-secondary)' }}>{row[2]}</td><td style={{ padding: 16, color: 'var(--text-secondary)' }}>{row[3]}</td></tr>)}</tbody></table></div><div style={{ marginTop: 10, color: 'var(--text-muted)', fontSize: 13 }}>Pricing data is publicly available from each provider&apos;s website.</div></section>
      <section style={{ maxWidth: 1240, margin: '0 auto', padding: '0 24px 80px' }}><div style={{ display: 'grid', gridTemplateColumns: 'repeat(3,minmax(0,1fr))', gap: 20 }}>{[{ name: 'Individual', price: '$9/mo', features: ['Intel feed', 'Overview', 'Conflict map', 'Recent alerts', 'Basic history'] }, { name: 'Pro', price: '$29/mo', features: ['Everything in Individual', 'ACH matrix', 'Monte Carlo', 'SAT tools', 'Forecasts', 'Travel briefs', 'Tracking layer'], highlight: true }, { name: 'Business', price: '$299/mo', features: ['Everything in Pro', 'API keys', 'Webhooks', 'Org management', 'Priority support', 'Higher limits', 'Auditability', 'Bulk exports', 'SLA', 'Admin tooling'] }].map((plan, idx) => <div key={idx} style={{ padding: 28, borderRadius: 16, border: `1px solid ${plan.highlight ? 'var(--primary)' : 'var(--border)'}`, background: 'var(--bg-surface)', position: 'relative' }}>{plan.highlight && <div style={{ position: 'absolute', top: 14, right: 14, background: 'var(--primary)', color: '#fff', padding: '6px 10px', borderRadius: 999, fontSize: 12, fontWeight: 600 }}>Most Popular</div>}<div style={{ fontSize: 20, fontWeight: 600 }}>{plan.name}</div><div style={{ marginTop: 10, fontSize: 38, fontWeight: 800 }}>{plan.price}</div><ul style={{ marginTop: 18, paddingLeft: 18, color: 'var(--text-secondary)', lineHeight: 1.8 }}>{plan.features.map((feature) => <li key={feature}>{feature}</li>)}</ul><Link href="/sign-up" style={{ display: 'inline-block', marginTop: 20, textDecoration: 'none', background: plan.highlight ? 'var(--primary)' : 'var(--bg-surface-2)', color: '#fff', padding: '12px 18px', borderRadius: 10 }}>Start Free</Link></div>)}</div></section>
      <footer style={{ borderTop: '1px solid var(--border)', padding: '28px 24px' }}><div style={{ maxWidth: 1240, margin: '0 auto', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}><div style={{ display: 'flex', gap: 20 }}><Link href="/features" style={{ color: 'var(--text-secondary)', textDecoration: 'none' }}>Features</Link><Link href="/pricing" style={{ color: 'var(--text-secondary)', textDecoration: 'none' }}>Pricing</Link><Link href="/privacy" style={{ color: 'var(--text-secondary)', textDecoration: 'none' }}>Privacy</Link><Link href="/terms" style={{ color: 'var(--text-secondary)', textDecoration: 'none' }}>Terms</Link></div><div style={{ color: 'var(--text-muted)' }}>© 2026 Conflict Ops</div></div></footer>
    </div>
  )
}
