'use client'
import { useEffect, useState } from 'react'
type Branding = { logo_url?: string; primary_color?: string; accent_color?: string; app_name?: string; custom_domain?: string }
export function BrandingEditor() {
  const [branding, setBranding] = useState<Branding>({ primary_color: '#2563eb', accent_color: '#f97316', app_name: 'ConflictRadar' })
  useEffect(() => { void fetch('/api/v1/enterprise/branding', { cache: 'no-store' }).then((r) => r.json()).then((json: { data?: Branding }) => setBranding((prev) => ({ ...prev, ...(json.data ?? {}) }))).catch(() => undefined) }, [])
  const save = async () => { await fetch('/api/v1/enterprise/branding', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(branding) }) }
  return <div className="grid gap-6 lg:grid-cols-[1fr_320px]"><div className="rounded-xl border p-4" style={{ borderColor: 'var(--border)', background: 'var(--bg-surface)' }}><div className="grid gap-3"><input value={branding.logo_url ?? ''} onChange={(e) => setBranding({ ...branding, logo_url: e.target.value })} placeholder="Logo URL" className="rounded border px-3 py-2 text-sm" style={{ borderColor: 'var(--border)', background: 'var(--bg-surface-2)', color: 'var(--text-primary)' }} /><div className="grid gap-3 md:grid-cols-2"><input type="color" value={branding.primary_color ?? '#2563eb'} onChange={(e) => setBranding({ ...branding, primary_color: e.target.value })} className="h-10 w-full rounded border" style={{ borderColor: 'var(--border)', background: 'var(--bg-surface-2)' }} /><input type="color" value={branding.accent_color ?? '#f97316'} onChange={(e) => setBranding({ ...branding, accent_color: e.target.value })} className="h-10 w-full rounded border" style={{ borderColor: 'var(--border)', background: 'var(--bg-surface-2)' }} /></div><input value={branding.app_name ?? ''} onChange={(e) => setBranding({ ...branding, app_name: e.target.value })} placeholder="App name" className="rounded border px-3 py-2 text-sm" style={{ borderColor: 'var(--border)', background: 'var(--bg-surface-2)', color: 'var(--text-primary)' }} /><input value={branding.custom_domain ?? ''} onChange={(e) => setBranding({ ...branding, custom_domain: e.target.value })} placeholder="Custom domain" className="rounded border px-3 py-2 text-sm" style={{ borderColor: 'var(--border)', background: 'var(--bg-surface-2)', color: 'var(--text-primary)' }} /><button onClick={() => void save()} className="rounded px-3 py-2 text-sm" style={{ background: 'var(--primary)', color: '#fff' }}>Save branding</button></div></div><div className="rounded-xl border p-4" style={{ borderColor: 'var(--border)', background: 'var(--bg-surface)' }}><div className="mb-3 text-sm font-semibold" style={{ color: 'var(--text-primary)' }}>Live preview</div><div className="rounded-xl p-4" style={{ background: branding.primary_color ?? '#2563eb' }}>{branding.logo_url ? <img src={branding.logo_url} alt="logo" className="mb-3 h-10 w-10 rounded" /> : null}<div className="text-lg font-semibold text-white">{branding.app_name ?? 'ConflictRadar'}</div><div className="mt-2 text-sm" style={{ color: branding.accent_color ?? '#f97316' }}>{branding.custom_domain ?? 'app.example.com'}</div></div></div></div>
}
