'use client'
import { useEffect, useState } from 'react'
type Branding = { logo_url?: string; primary_color?: string; accent_color?: string; app_name?: string; custom_domain?: string }
export function BrandingEditor() {
  const [branding, setBranding] = useState<Branding>({ primary_color: '#2563eb', accent_color: '#f97316', app_name: 'ConflictRadar' })
  useEffect(() => { void fetch('/api/v1/enterprise/branding', { cache: 'no-store' }).then((r) => r.json()).then((json: { data?: Branding }) => setBranding((prev) => ({ ...prev, ...(json.data ?? {}) }))).catch(() => undefined) }, [])
  const [saveStatus, setSaveStatus] = useState<'idle' | 'saving' | 'saved' | 'error'>('idle')
  const save = async () => { setSaveStatus('saving'); try { const res = await fetch('/api/v1/enterprise/branding', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(branding) }); setSaveStatus(res.ok ? 'saved' : 'error'); setTimeout(() => setSaveStatus('idle'), 2000) } catch { setSaveStatus('error'); setTimeout(() => setSaveStatus('idle'), 2000) } }
  return <div className="grid gap-6 lg:grid-cols-[1fr_320px]"><div className="rounded-xl border border-white/[0.05] bg-white/[0.015] p-4"><div className="grid gap-3"><input value={branding.logo_url ?? ''} onChange={(e) => setBranding({ ...branding, logo_url: e.target.value })} placeholder="Logo URL" className="rounded border border-white/[0.05] bg-white/[0.03] px-3 py-2 text-sm text-white placeholder:text-white/20" /><div className="grid gap-3 md:grid-cols-2"><input type="color" value={branding.primary_color ?? '#2563eb'} onChange={(e) => setBranding({ ...branding, primary_color: e.target.value })} className="h-10 w-full rounded border border-white/[0.05]" /><input type="color" value={branding.accent_color ?? '#f97316'} onChange={(e) => setBranding({ ...branding, accent_color: e.target.value })} className="h-10 w-full rounded border border-white/[0.05]" /></div><input value={branding.app_name ?? ''} onChange={(e) => setBranding({ ...branding, app_name: e.target.value })} placeholder="App name" className="rounded border border-white/[0.05] bg-white/[0.03] px-3 py-2 text-sm text-white placeholder:text-white/20" /><input value={branding.custom_domain ?? ''} onChange={(e) => setBranding({ ...branding, custom_domain: e.target.value })} placeholder="Custom domain" className="rounded border border-white/[0.05] bg-white/[0.03] px-3 py-2 text-sm text-white placeholder:text-white/20" /><button onClick={() => void save()} disabled={saveStatus === 'saving'} className="rounded px-3 py-2 text-sm text-white" style={{ background: saveStatus === 'saved' ? '#10B981' : saveStatus === 'error' ? '#EF4444' : '#3b82f6' }}>{saveStatus === 'saving' ? 'Saving...' : saveStatus === 'saved' ? 'Saved!' : saveStatus === 'error' ? 'Failed — retry' : 'Save branding'}</button></div></div><div className="rounded-xl border border-white/[0.05] bg-white/[0.015] p-4"><div className="mb-3 text-sm font-semibold text-white">Live preview</div><div className="rounded-xl p-4" style={{ background: branding.primary_color ?? '#2563eb' }}>{branding.logo_url ? <img src={branding.logo_url} alt="logo" className="mb-3 h-10 w-10 rounded" /> : null}<div className="text-lg font-semibold text-white">{branding.app_name ?? 'ConflictRadar'}</div><div className="mt-2 text-sm" style={{ color: branding.accent_color ?? '#f97316' }}>{branding.custom_domain ?? 'app.example.com'}</div></div></div></div>
}
