'use client'

import { useState } from 'react'
import { GeoverifyPanel } from '@/components/geoverify/GeoverifyPanel'

export default function GeoverifyPage() {
  const [lat, setLat] = useState('31.7767')
  const [lng, setLng] = useState('35.2345')
  const [timestamp, setTimestamp] = useState(new Date().toISOString().slice(0,16))
  const [sun, setSun] = useState<{ azimuth: number; elevation: number } | null>(null)
  const [imageUrl, setImageUrl] = useState('')
  const [exif, setExif] = useState<string>('')
  const [sunError, setSunError] = useState('')
  const [exifError, setExifError] = useState('')
  const runSun = async () => { setSunError(''); try { const res = await fetch(`/api/v1/geoverify?action=suncalc&lat=${encodeURIComponent(lat)}&lng=${encodeURIComponent(lng)}&timestamp=${encodeURIComponent(new Date(timestamp).toISOString())}`); if (!res.ok) throw new Error(`HTTP ${res.status}`); const json = await res.json() as { data?: { azimuth: number; elevation: number } }; setSun(json.data ?? null) } catch (err) { setSunError(err instanceof Error ? err.message : 'Request failed') } }
  const runExif = async () => { setExifError(''); try { const res = await fetch('/api/v1/geoverify?action=exif', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ image_url: imageUrl }) }); if (!res.ok) throw new Error(`HTTP ${res.status}`); const json = await res.json() as { data?: { metadata?: unknown } }; setExif(JSON.stringify(json.data?.metadata ?? { available: false }, null, 2)) } catch (err) { setExifError(err instanceof Error ? err.message : 'Request failed') } }
  const mapSrc = `https://www.openstreetmap.org/export/embed.html?bbox=${Number(lng)-0.2}%2C${Number(lat)-0.2}%2C${Number(lng)+0.2}%2C${Number(lat)+0.2}&layer=mapnik&marker=${lat}%2C${lng}`
  return <div className="p-6 space-y-6"><GeoverifyPanel /><div className="grid gap-6 xl:grid-cols-2"><div className="rounded-xl border border-white/[0.05] bg-white/[0.015] p-4"><div className="mb-3 text-sm font-semibold text-white">SunCalc shadow analysis</div><div className="grid gap-3 md:grid-cols-3"><input value={lat} onChange={(e) => setLat(e.target.value)} className="rounded border border-white/[0.05] bg-white/[0.03] px-3 py-2 text-sm text-white" /><input value={lng} onChange={(e) => setLng(e.target.value)} className="rounded border border-white/[0.05] bg-white/[0.03] px-3 py-2 text-sm text-white" /><input type="datetime-local" value={timestamp} onChange={(e) => setTimestamp(e.target.value)} className="rounded border border-white/[0.05] bg-white/[0.03] px-3 py-2 text-sm text-white" /></div><button onClick={() => void runSun()} className="mt-3 rounded bg-blue-500 px-3 py-2 text-sm text-white">Compute sun position</button>{sunError ? <div className="mt-3 text-sm text-red-400">{sunError}</div> : sun ? <div className="mt-3 text-sm text-white/50">Azimuth {sun.azimuth.toFixed(1)}° · Elevation {sun.elevation.toFixed(1)}°</div> : null}</div><div className="rounded-xl border border-white/[0.05] bg-white/[0.015] p-4"><div className="mb-3 text-sm font-semibold text-white">Reverse image metadata extractor</div><div className="flex gap-2"><input value={imageUrl} onChange={(e) => setImageUrl(e.target.value)} placeholder="https://..." className="flex-1 rounded border border-white/[0.05] bg-white/[0.03] px-3 py-2 text-sm text-white" /><button onClick={() => void runExif()} className="rounded bg-blue-500 px-3 py-2 text-sm text-white">Extract EXIF</button></div><pre className="mt-3 overflow-auto rounded-lg bg-white/[0.03] p-3 text-xs text-white/50">{exifError ? <span className="text-red-400">{exifError}</span> : (exif || 'No EXIF query run yet.')}</pre></div></div><div className="grid gap-6 xl:grid-cols-2"><div className="rounded-xl border border-white/[0.05] bg-white/[0.015] p-4"><div className="mb-3 text-sm font-semibold text-white">Submitted image / coordinates</div>{imageUrl ? <img src={imageUrl} alt="submitted" className="max-h-[420px] w-full rounded-lg object-contain" /> : <div className="rounded-lg border border-white/[0.05] p-10 text-sm text-center text-white/30">Add an image URL above.</div>}</div><div className="rounded-xl border border-white/[0.05] bg-white/[0.015] p-4"><div className="mb-3 text-sm font-semibold text-white">Terrain match / satellite reference</div><iframe title="satellite-reference" src={mapSrc} className="h-[420px] w-full rounded-lg border-0" /><div className="mt-2 text-xs text-white/30">MapLibre/DEM-ready slot wired as a side-by-side reference. Current fallback uses OSM embed when private tiles are unavailable.</div></div></div></div>
}
