export const PLANS = [
  {
    id: 'individual',
    name: 'Individual',
    price: '$9',
    priceMonthly: 9,
    period: '/mo',
    desc: 'For solo analysts and researchers',
    stripePriceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_INDIVIDUAL ?? 'price_individual',
    features: ['3 alert rules', '7-day event history', 'Intel feed + map', 'Basic forecasts', 'Email alerts'],
    popular: false,
  },
  {
    id: 'pro',
    name: 'Pro',
    price: '$29',
    priceMonthly: 29,
    period: '/mo',
    desc: 'For professional analysts',
    stripePriceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_PRO ?? 'price_pro',
    features: ['25 alert rules', '180-day history', 'AI Co-pilot', 'Workbench tools', 'Scheduled briefs', 'API access'],
    popular: true,
  },
  {
    id: 'business',
    name: 'Business',
    price: '$299',
    priceMonthly: 299,
    period: '/mo',
    desc: 'For teams and security firms',
    stripePriceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_BUSINESS ?? 'price_business',
    features: ['Unlimited alert rules', '365-day history', 'Full API + webhooks', 'Slack/PagerDuty', 'Team seats (10)', 'Audit logs'],
    popular: false,
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    price: 'Custom',
    priceMonthly: null as number | null,
    period: '',
    desc: 'For large organisations',
    stripePriceId: null as string | null,
    features: ['Unlimited everything', 'SSO/SAML', 'White-label branding', 'Custom data sources', 'Dedicated support', 'SLA'],
    popular: false,
  },
] as const
