'use client'

import { useEffect, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { BarChart3 } from 'lucide-react'
import { MonteCarloEngine } from '@/components/workbench/MonteCarloEngine'
import { ACHMatrix } from '@/components/workbench/ACHMatrix'
import { SATTools } from '@/components/workbench/SATTools'

type ForecastRow = { id: string; country_code?: string | null; region?: string | null; score?: number | null; event_count?: number | null; updated_at?: string | null }
const TABS = ['Monte Carlo', 'ACH Matrix', 'SAT Tools', 'Forecasts'] as const
function timeAgo(input?: string | null) { if (!input) return 'unknown'; const diff = Math.max(0, Date.now() - new Date(input).getTime()); const mins = Math.floor(diff / 60000); if (mins < 60) return `${mins}m ago`; const hours = Math.floor(mins / 60); if (hours < 24) return `${hours}h ago`; return `${Math.floor(hours / 24)}d ago` }

export default function WorkbenchPage() {
  const BarChart3Icon = BarChart3 as any
  const [activeTab, setActiveTab] = useState<(typeof TABS)[number]>('Monte Carlo')
  const [forecasts, setForecasts] = useState<ForecastRow[]>([])
  useEffect(() => { if (activeTab !== 'Forecasts') return; void fetch('/api/v1/forecasts', { cache: 'no-store' }).then((r) => r.json()).then((json: { data?: ForecastRow[] }) => setForecasts(json.data ?? [])) }, [activeTab])
  return <div className="h-full"><div className="border-b px-4" style={{ borderColor: 'var(--border)' }}>{TABS.map((tab) => <button key={tab} onClick={() => setActiveTab(tab)} className="px-4 py-3 text-sm font-medium active:scale-[0.97]" style={{ borderBottom: activeTab === tab ? '2px solid var(--primary)' : '2px solid transparent', color: activeTab === tab ? 'var(--primary)' : 'var(--text-muted)' }}>{tab}</button>)}</div><div className="p-6"><AnimatePresence mode="wait"><motion.div key={activeTab} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }} transition={{ duration: 0.2 }}>{activeTab === 'Monte Carlo' && <MonteCarloEngine planHasScenarios />}{activeTab === 'ACH Matrix' && <ACHMatrix planHasACH />}{activeTab === 'SAT Tools' && <SATTools />}{activeTab === 'Forecasts' && <div className="rounded-xl border" style={{ borderColor: 'var(--border)', background: 'var(--bg-surface)' }}>{forecasts.length === 0 ? <div className="flex flex-col items-center justify-center gap-3 p-10 text-center"><BarChart3Icon size={32} style={{ color: 'var(--text-muted)' }} /><div style={{ color: 'var(--text-primary)' }}>Run ingest to generate forecasts</div><a href="/admin" className="rounded-lg px-3 py-2 text-sm btn-primary" style={{ background: 'var(--primary)', color: '#fff' }}>Go to Admin</a></div> : <table className="w-full text-sm"><thead><tr className="text-left" style={{ color: 'var(--text-muted)' }}><th className="px-4 py-3">Region</th><th className="px-4 py-3">P50 Score</th><th className="px-4 py-3">Events 7d</th><th className="px-4 py-3">Updated</th></tr></thead><tbody>{forecasts.map((row) => { const pct = Math.round((row.score ?? 0) * 100); return <tr key={row.id} className="border-t" style={{ borderColor: 'var(--border)' }}><td className="px-4 py-3" style={{ color: 'var(--text-primary)' }}>{row.region || row.country_code || 'Unknown'}</td><td className="px-4 py-3"><div className="flex items-center gap-3"><div className="h-2 w-40 rounded-full" style={{ background: 'var(--bg-surface-3)' }}><div className="h-full rounded-full" style={{ width: `${pct}%`, background: pct > 70 ? 'var(--sev-critical)' : pct > 40 ? 'var(--sev-medium)' : 'var(--sev-low)' }} /></div><span style={{ color: 'var(--text-primary)', fontFamily: 'JetBrains Mono, monospace' }}>{pct}%</span></div></td><td className="px-4 py-3" style={{ color: 'var(--text-primary)', fontFamily: 'JetBrains Mono, monospace' }}>{row.event_count ?? 0}</td><td className="px-4 py-3" style={{ color: 'var(--text-muted)' }}>{timeAgo(row.updated_at)}</td></tr> })}</tbody></table>}</div>}</motion.div></AnimatePresence></div></div>
}
