'use client'
import { useState } from 'react'
type Result = { narrative: string; risk_tier: string; event_count: number; xbrl_json: Record<string, unknown> }
export function ESGReportBuilder() {
  const [orgId, setOrgId] = useState('')
  const [countries, setCountries] = useState('UA,IL,SD')
  const [start, setStart] = useState(new Date(Date.now() - 30*86400000).toISOString().slice(0,10))
  const [end, setEnd] = useState(new Date().toISOString().slice(0,10))
  const [result, setResult] = useState<Result | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const generate = async () => { setLoading(true); setError(null); try { const res = await fetch('/api/v1/reports/esg', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ org_id: orgId, country_codes: countries.split(',').map((item) => item.trim().toUpperCase()).filter(Boolean), date_range: { start, end } }) }); if (!res.ok) { setError('Failed to generate report'); return } const json = await res.json() as { data?: Result }; setResult(json.data ?? null); if (!json.data) setError('No data returned') } catch { setError('Network error generating report') } finally { setLoading(false) } }
  const exportJson = () => { if (!result) return; const blob = new Blob([JSON.stringify(result.xbrl_json, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'esg-report.json'; a.click(); URL.revokeObjectURL(url) }
  return <div className="space-y-4"><div className="grid gap-3 md:grid-cols-4"><input value={orgId} onChange={(e) => setOrgId(e.target.value)} placeholder="Org ID" className="rounded border px-3 py-2 text-sm bg-white/[0.015] border-white/[0.05] text-white" /><input value={countries} onChange={(e) => setCountries(e.target.value)} placeholder="UA,IL,SD" className="rounded border px-3 py-2 text-sm bg-white/[0.015] border-white/[0.05] text-white" /><input type="date" value={start} onChange={(e) => setStart(e.target.value)} className="rounded border px-3 py-2 text-sm bg-white/[0.015] border-white/[0.05] text-white" /><input type="date" value={end} onChange={(e) => setEnd(e.target.value)} className="rounded border px-3 py-2 text-sm bg-white/[0.015] border-white/[0.05] text-white" /></div><div className="flex gap-2"><button onClick={() => void generate()} disabled={loading} className="rounded px-3 py-2 text-sm bg-blue-500 text-white">{loading ? 'Generating...' : 'Generate Report'}</button>{result ? <><button onClick={exportJson} className="rounded border px-3 py-2 text-sm border-white/[0.05] text-white">Export JSON (XBRL-ready)</button><button onClick={() => window.print()} className="rounded border px-3 py-2 text-sm border-white/[0.05] text-white">Print PDF</button></> : null}</div>{error ? <div className="p-3 rounded border text-xs mono border-red-400 text-red-400">{error}</div> : null}{result ? <div className="rounded-xl border p-4 bg-white/[0.015] border-white/[0.05]"><div className="mb-2 flex gap-3"><span className="rounded-full px-2 py-1 text-xs bg-blue-500/20 text-blue-400">{result.risk_tier.toUpperCase()}</span><span className="text-sm text-white/50">{result.event_count} events</span></div><div className="whitespace-pre-wrap text-sm text-white">{result.narrative}</div></div> : null}</div>
}
